const fs = require("fs");
const pokeMarkov = require("./poke-markov.js");

const startingTeam = [
    {name: "Slowpoke"},
    {name: "Slowpoke-Galar"},
    {name: "Buneary"},
    {name: "Lopunny"},
    {name: "Chansey"},
    {name: "Blissey"},
]; // example starting team

const allPokemonInfo = JSON.parse(
    fs.readFileSync("../data-retrieval/output/homebss-1760.json")
); // example format data

const formatAllowedPokemonList = [
// placeholder for testing - filter down the format to only Isle of Armor Pokemon
"Slowpoke",
"Slowpoke-Galar",
"Slowbro",
"Slowbro-Galar",
"Slowking",
"Buneary",
"Lopunny",
// "Happiny",
"Chansey",
"Blissey",
// "Skwovet",
"Greedent",
// "Igglybuff",
"Jigglypuff",
"Wigglytuff",
"Dottler",
"Orbeetle",
"Fomantis",
"Lurantis",
"Flapple",
"Appletun",
"Fletchling",
// "Fletchinder",
"Talonflame",
"Shinx",
// "Luxio",
"Luxray",
"Klefki",
"Pawniard",
"Bisharp",
// "Abra",
"Kadabra",
"Alakazam",
"Ralts",
"Kirlia",
"Gardevoir",
"Gallade",
"Krabby",
"Kingler",
"Tentacool",
"Tentacruel",
"Magikarp",
"Gyarados",
// "Remoraid",
"Octillery",
// "Mantyke",
"Mantyne",
// "Wingull",
"Pelipper",
// "Skorupi",
"Drapion",
"Dunsparce",
"Bouffalant",
"Lickitung",
"Lickilicky",
// "Chewtle",
"Drednaw",
// "Wooper",
"Quagsire",
// "Goomy",
"Sliggoo",
"Goodra",
"Druddigon",
// "Shelmet",
"Accelgor",
// "Karrablast",
"Escavalier",
// "Bulbasaur",
// "Ivysaur",
"Venusaur",
// "Squirtle",
"Wartortle",
"Blastoise",
// "Venipede",
"Whirlipede",
"Scolipede",
"Foongus",
"Amoonguss",
"Comfey",
"Tangela",
"Tangrowth",
// "Croagunk",
"Toxicroak",
// "Pichu",
"Pikachu",
"Raichu",
"Raichu-Alola",
"Zorua",
"Zoroark",
"Oranguru",
"Passimian",
"Corphish",
"Crawdaunt",
"Cramorant",
// "Goldeen",
"Seaking",
"Arrokuda",
"Barraskewda",
"Staryu",
"Starmie",
// "Kubfu",
"Urshifu",
"Urshifu-Rapid-Strike",
"Emolga",
"Dedenne",
"Morpeko",
// "Magnemite",
"Magneton",
"Magnezone",
"Inkay",
"Malamar",
"Wishiwashi",
// "Carvanha",
"Sharpedo",
// "Lillipup",
// "Herdier",
"Stoutland",
"Tauros",
"Miltank",
"Scyther",
"Scizor",
"Pinsir",
"Heracross",
// "Dwebble",
"Crustle",
"Wimpod",
"Golisopod",
"Pincurchin",
// "Mareanie",
"Toxapex",
// "Clobbopus",
"Grapploct",
// "Shellder",
"Cloyster",
"Sandygast",
"Palossand",
// "Drifloon",
"Drifblim",
"Barboach",
"Whiscash",
// "Azurill",
"Marill",
"Azumarill",
// "Poliwag",
"Poliwhirl",
"Poliwrath",
"Politoed",
"Psyduck",
"Golduck",
// "Whismur",
// "Loudred",
"Exploud",
// "Woobat",
"Swoobat",
"Skarmory",
// "Roggenrola",
"Boldore",
"Gigalith",
// "Rockruff",
"Lycanroc",
"Lycanroc-Midnight",
"Lycanroc-Dusk",
// "Salandit",
"Salazzle",
// "Scraggy",
"Scrafty",
"Mienfoo",
"Mienshao",
// "Jangmo-o",
// "Hakamo-o",
"Kommo-o",
"Sandshrew",
"Sandshrew-Alola",
"Sandslash",
"Sandslash-Alola",
"Cubone",
"Marowak",
"Kangaskhan",
"Torkoal",
// "Silicobra",
"Sandaconda",
"Sandile",
// "Krokorok",
"Krookodile",
// "Rufflet",
"Braviary",
// "Vullaby",
"Mandibuzz",
"Rhyhorn",
"Rhydon",
"Rhyperior",
"Larvesta",
"Volcarona",
// "Chinchou",
"Lanturn",
// "Wailmer",
"Wailord",
"Frillish",
"Jellicent",
"Skrelp",
"Dragalge",
// "Clauncher",
"Clawitzer",
// "Horsea",
"Seadra",
"Kingdra",
"Petilil",
"Lilligant",
// "Combee",
"Vespiquen",
// "Exeggcute",
"Exeggutor",
"Exeggutor-Alola",
"Ditto",
"Porygon",
"Porygon2",
"Porygon-Z",
// "Zarude",
]



const unfilteredPokemonList = Object.keys(allPokemonInfo);

unfilteredPokemonList.forEach(pokemon => {
    if (!formatAllowedPokemonList.includes(pokemon)) {
        delete allPokemonInfo[pokemon];
    }
});
Object.values(allPokemonInfo).forEach(pokemon => {
    pokemon.team = pokemon.team.filter(pokemon =>
        formatAllowedPokemonList.includes(pokemon.pokemon)
    );
    pokemon.counters = pokemon.counters.filter(pokemon =>
        formatAllowedPokemonList.includes(pokemon.pokemon)
    );

  });

const numberOfSteps = 10000;

console.log("Running algorithm with the following starting team:");
console.log(startingTeam);

console.log(`Number of steps: ${numberOfSteps}`);

const resultTeam = pokeMarkov(startingTeam, allPokemonInfo, numberOfSteps);

console.log("Result of running algorithm:");
console.log(resultTeam);
